site_name: Siddhi-Store-RDBMS
extra_css:
- stylesheets/extra.css
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
pages:
- Welcome to WSO2 Siddhi Store RDBMS: index.md
- About:
  - License: about/license.md
- Api:
  - 4.0.0-M3-SNAPSHOT: api/4.0.0-M3-SNAPSHOT.md
theme: material
