site_name: Siddhi-Store-RDBMS
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Store RDBMS: index.md
- API Docs:
  - 4.0.2: api/4.0.2.md
  - 4.0.1: api/4.0.1.md
  - latest: api/latest.md
- License: license.md
theme: material
