site_name: Siddhi-Store-RDBMS
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Store RDBMS: index.md
- API Docs:
  - 4.0.17: api/4.0.17.md
  - 4.0.16: api/4.0.16.md
  - 4.0.15: api/4.0.15.md
  - 4.0.14: api/4.0.14.md
  - 4.0.13: api/4.0.13.md
  - 4.0.12: api/4.0.12.md
  - 4.0.11: api/4.0.11.md
  - 4.0.10: api/4.0.10.md
  - 4.0.9: api/4.0.9.md
  - 4.0.8: api/4.0.8.md
  - 4.0.7: api/4.0.7.md
  - 4.0.6: api/4.0.6.md
  - 4.0.5: api/4.0.5.md
  - 4.0.4: api/4.0.4.md
  - 4.0.3: api/4.0.3.md
  - 4.0.2: api/4.0.2.md
  - 4.0.1: api/4.0.1.md
  - latest: api/latest.md
- License: license.md
theme: material
